### ISSUE TITLE
Missing categories

### ISSUE THREAD

**Issue by tursynay** [deepakunni3/biolink-monarch-kg#2]
Nodes in the graph don't have the full set of categories on them as labels. For instance

match (c:biolink:NamedThing {id:"GO:0015254"}) return labels(c)

returns

["biolink:NamedThing", "biolink:Occurrent", "biolink:MolecularActivity"]

Which are some of the categories for the node, but not all of them. In particular, there's no biolink:BiologicalProcessOrActivity, which is a nice one to use in queries.

The reason that this matters is because Plater uses these labels to do its queries. So even though this GO node is a BiologicalProcessOrActivity, it will not be returned for queries that use that category.

This issue was originally created on April 22, 2021 here (the repo is archived) by @cbizon: https://github.com/TranslatorSRI/reference-kg/issues/11

**Comment by tursynay** [comment]
@deepakunni3, hi :)

The old reference KG repo that was in SRI org got archived and we cannot create new issues there for this. This new location only has you as a member. Would you be adding more members or could you reopen the old repo for us? We need to assign this ticket to Kent and we can't do in either place :)

**Comment by kshefchek** [comment]
@nlharris @tursynay I'm not sure the best way to resolve the access issues, is there a way to add a SRI team to this repo?  If it's too complicated maybe the best approach would be to fork or copy this into the SRI org? I can also unarchive the sri reference-kg repo if that's easiest

**Comment by tursynay** [comment]
@kshefchek, thank you.  @cbizon, which would you prefer? Kent suggested the two options below:

> I'm not sure the best way to resolve the access issues, is there a way to add a SRI team to this repo? If it's too complicated maybe the best approach would be to fork or copy this into the SRI org? I can also unarchive the sri reference-kg repo if that's easiest.

**Comment by cbizon** [comment]
Either is fine.  I would probably just unarchive the one that's already there, but not sure if there's things in this repo we'd like in that one.

**Comment by kshefchek** [comment]
i've unarchived https://github.com/TranslatorSRI/reference-kg and added a note there that the code to generate the graph lives here

**Comment by tursynay** [comment]
@kshefchek, thanks for unarchiving the reference kg repo, I assigned the original issue create by @cbizon [here](https://github.com/TranslatorSRI/reference-kg/issues/11).

**Comment by tursynay** [comment]
closing
